-- ==============================================================================
-- 1. MODULE NGƯỜI DÙNG & PHÂN QUYỀN (USER & AUTHENTICATION)
-- ==============================================================================

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(100) UNIQUE                NOT NULL,
    user_name     VARCHAR(100) UNIQUE                NOT NULL,
    password      VARCHAR(255)                       NOT NULL,
    pin           VARCHAR(64)                        NOT NULL,
    pin_wrong     SMALLINT                 DEFAULT 0 NOT NULL,
    img           VARCHAR(255),
    theme         SMALLINT                 DEFAULT 0 NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE,
    locked_until  TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email));
CREATE UNIQUE INDEX uq_users_user_name_lower ON users (LOWER(user_name));


CREATE TABLE tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token      TEXT UNIQUE              NOT NULL,
    token_type VARCHAR(20)              NOT NULL,
    ip_address VARCHAR(45)              NOT NULL,
    user_agent TEXT                     NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tokens_user_type_expiry
    ON tokens (user_id, token_type, expires_at);


CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE role_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (role_id, permission_id)
);

CREATE TABLE user_roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id    BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, role_id)
);


-- ==============================================================================
-- 2. MODULE TỪ ĐIỂN CỐT LÕI (CORE DICTIONARY)
-- ==============================================================================

CREATE TABLE english_words
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word      VARCHAR(255) NOT NULL,
    phonetic  VARCHAR(255),
    audio_url TEXT
);

CREATE TABLE vietnamese_meanings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translation VARCHAR(255) NOT NULL,
    description TEXT
);


-- ==============================================================================
-- 3. MODULE HỌC TẬP & LẶP LẠI NGẮT QUÃNG (SRS & FLASHCARDS)
-- ==============================================================================

CREATE TABLE user_vocabularies
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT                               NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    english_id          BIGINT                               NOT NULL REFERENCES english_words (id) ON DELETE RESTRICT,
    vietnamese_id       BIGINT                               NOT NULL REFERENCES vietnamese_meanings (id) ON DELETE RESTRICT,
    part_of_speech      VARCHAR(25),
    image_url           TEXT,

    -- SRS Fields
    ease_factor         REAL                     DEFAULT 2.5 NOT NULL,
    interval_days       INTEGER                  DEFAULT 0   NOT NULL,
    consecutive_correct INTEGER                  DEFAULT 0   NOT NULL,
    next_review_date    TIMESTAMP WITH TIME ZONE,

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_practiced_at   TIMESTAMP WITH TIME ZONE,

    UNIQUE (user_id, english_id, vietnamese_id, part_of_speech)
);

CREATE TABLE review_logs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_vocabulary_id BIGINT      NOT NULL REFERENCES user_vocabularies (id) ON DELETE CASCADE,
    user_id            BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    question_type      VARCHAR(50) NOT NULL,
    grade              SMALLINT    NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_vocab_review_date ON user_vocabularies (user_id, next_review_date);


-- ==============================================================================
-- 4. MODULE ĐỌC HIỂU CHUYÊN Sâu (READING MATERIALS & INSIGHTS)
-- ==============================================================================

CREATE TABLE reading_materials
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    original_text    TEXT         NOT NULL,
    reading_priority VARCHAR(20)              DEFAULT 'MAIN',
    user_id          BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reading_annotations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id   BIGINT NOT NULL REFERENCES reading_materials (id) ON DELETE CASCADE,
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    selected_text TEXT   NOT NULL,
    explanation   TEXT   NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reading_reflections
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id           BIGINT NOT NULL REFERENCES reading_materials (id) ON DELETE CASCADE,
    user_id               BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    practical_application TEXT,
    shared_notes          TEXT,
    created_at            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ==============================================================================
-- 5. MODULE RÈN LUYỆN KỶ LUẬT & KỸ NĂNG VIẾT (DAILY JOURNALING)
-- ==============================================================================

CREATE TABLE daily_journals
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    entry_date              DATE   NOT NULL,
    lessons_learned         TEXT,
    gratitude_notes         TEXT,
    behavioral_improvements TEXT,
    created_at              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, entry_date)
);