import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import { corsOptions } from './config/cors.js';
import { requestLogger } from './shared/middlewares/request-logger.js';
import { generalRateLimiter } from './shared/middlewares/rate-limiter.js';
import { errorHandler } from './shared/middlewares/error.handler.js';
import { systemRouter } from './modules/system/system.routes.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { usersRouter } from './modules/users/users.routes.js';
import { topicTreesRouter } from './modules/topic-trees/topic-trees.routes.js';
import { vocabularyRouter } from './modules/vocabulary/vocabulary.routes.js';
import { publishingRouter } from './modules/publishing/publishing.routes.js';
import { collaborationRouter } from './modules/collaboration/collaboration.routes.js';
import { queriesRouter } from './modules/queries/queries.routes.js';
import { importsRouter } from './modules/imports/imports.routes.js';
import { studyRouter } from './modules/study/study.routes.js';
import { operationsRouter } from './modules/operations/operations.routes.js';
import { adminRouter } from './modules/admin/admin.routes.js';
import { env } from './config/env.js';

export function createApp() {
  const app = express();
  app.disable('x-powered-by');
  app.use(requestLogger as any);
  app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }) as any);
  app.use(cors(corsOptions) as any);
  app.use(cookieParser(env.COOKIE_SECRET) as any);
  app.use(express.json({ limit: '2mb' }));
  app.use(express.urlencoded({ extended: true }));
  app.use(generalRateLimiter as any);

  const api = express.Router();
  api.use(systemRouter);
  api.use('/auth', authRouter);
  api.use('/me', usersRouter);
  api.use(topicTreesRouter);
  api.use(vocabularyRouter);
  api.use(publishingRouter);
  api.use(collaborationRouter);
  api.use(queriesRouter);
  api.use(importsRouter);
  api.use(studyRouter);
  api.use(operationsRouter);
  api.use(adminRouter);
  app.use(env.API_PREFIX, api);
  app.use((_req, res) => res.status(404).json({ title: 'Route not found', status: 404, code: 'ROUTE_NOT_FOUND' }));
  app.use(errorHandler as any);
  return app;
}
export const app = createApp();
