import { randomUUID } from 'node:crypto';
import { hashPasswordSync, verifyPassword } from '../../shared/utils/hash.js';
import { nowIso, addDays } from '../../shared/utils/date.js';
import { normalizeText, slugify } from '../../shared/utils/string.js';
import { ConflictError, ForbiddenError, NotFoundError, ValidationError } from '../../shared/errors/app-error.js';
import { paginate } from '../../shared/pagination/paginate.js';
import type { AccessRole, AuditRecord, CollaboratorRecord, ImportJobRecord, ImportRowRecord, NodeRecord, OperationRecord, PronunciationRecord, PublicationRecord, SavedQueryRecord, StudySessionRecord, TreeRecord, UserRecord, VocabularyRecord } from '../../domain/models.js';
import { evaluateQuery, parseQuery } from '../../modules/queries/query-engine.js';

const MAX_DEPTH = 8;
const PUBLIC_USER_FIELDS = (user: UserRecord) => ({ id: user.id, display_name: user.displayName, avatar_url: user.avatarUrl });

export class MemoryStore {
  users = new Map<string, UserRecord>();
  trees = new Map<string, TreeRecord>();
  nodes = new Map<string, NodeRecord>();
  vocabularies = new Map<string, VocabularyRecord>();
  publications = new Map<string, PublicationRecord>();
  collaborators = new Map<string, CollaboratorRecord>();
  savedQueries = new Map<string, SavedQueryRecord>();
  operations = new Map<string, OperationRecord>();
  imports = new Map<string, ImportJobRecord>();
  studySessions = new Map<string, StudySessionRecord>();
  pronunciationAttempts = new Map<string, PronunciationRecord>();
  auditLogs: AuditRecord[] = [];
  refreshTokens = new Map<string, { userId: string; expiresAt: number; familyId: string }>();
  private auditSequence = 1;

  constructor() { this.seed(); }

  reset() {
    this.users.clear(); this.trees.clear(); this.nodes.clear(); this.vocabularies.clear(); this.publications.clear();
    this.collaborators.clear(); this.savedQueries.clear(); this.operations.clear(); this.imports.clear();
    this.studySessions.clear(); this.pronunciationAttempts.clear(); this.auditLogs = []; this.refreshTokens.clear();
    this.auditSequence = 1; this.seed();
  }

  private seed() {
    const learner = this.addUser('learner@lexigo.local', 'Demo User', 'Demo123!', ['LEARNER']);
    const admin = this.addUser('admin@lexigo.local', 'LexiGo Admin', 'Admin123!', ['LEARNER', 'ADMIN']);
    const tree = this.createTree(learner.id, { display_name: 'English for Product Team', description: 'Từ vựng sản phẩm, thiết kế và kỹ thuật.' });
    const product = this.createNode(learner.id, tree.id, { parent_id: null, display_name: 'Product', description: 'Product discovery and delivery', node_type: 'GROUP' });
    const discovery = this.createNode(learner.id, tree.id, { parent_id: product.id, display_name: 'Discovery', description: null, node_type: 'VOCABULARY' });
    const engineering = this.createNode(learner.id, tree.id, { parent_id: null, display_name: 'Engineering', description: 'Software engineering topics', node_type: 'GROUP' });
    const frontend = this.createNode(learner.id, tree.id, { parent_id: engineering.id, display_name: 'Frontend', description: null, node_type: 'VOCABULARY' });
    for (const item of [
      ['hypothesis', 'giả thuyết', '/haɪˈpɒθəsɪs/', 'NOUN', 'We test the riskiest hypothesis first.'],
      ['persona', 'chân dung người dùng', '/pəˈsəʊnə/', 'NOUN', 'The persona represents a target learner.'],
      ['backlog', 'danh sách công việc tồn đọng', '/ˈbæklɒɡ/', 'NOUN', 'The team refined the backlog.'],
    ]) this.createVocabulary(learner.id, discovery.id, { english: item[0], vietnamese: item[1], pronunciation: item[2], part_of_speech: item[3], example: item[4] });
    for (const item of [
      ['component', 'thành phần giao diện', '/kəmˈpəʊnənt/', 'NOUN', 'A component should be reusable.'],
      ['render', 'kết xuất', '/ˈrendə/', 'VERB', 'React renders the view.'],
      ['accessible', 'có thể tiếp cận', '/əkˈsesəbəl/', 'ADJECTIVE', 'The interface is accessible by keyboard.'],
    ]) this.createVocabulary(learner.id, frontend.id, { english: item[0], vietnamese: item[1], pronunciation: item[2], part_of_speech: item[3], example: item[4] });
    const adminTree = this.createTree(admin.id, { display_name: 'Daily English A1', description: 'Default curriculum for beginners.' }, 'DEFAULT');
    const daily = this.createNode(admin.id, adminTree.id, { parent_id: null, display_name: 'Daily Life', description: null, node_type: 'VOCABULARY' });
    this.createVocabulary(admin.id, daily.id, { english: 'family', vietnamese: 'gia đình', pronunciation: '/ˈfæməli/', part_of_speech: 'NOUN', example: 'My family lives in Vietnam.' });
    const publication = this.publish(admin.id, adminTree.id, { scope: 'TREE', root_node_id: null, draft_revision: this.trees.get(adminTree.id)!.draftRevision, display_name: 'Daily English A1', description: 'Starter vocabulary.' });
    this.audit(admin.id, 'SEED_CREATED', 'SYSTEM', null, null, { publication_id: publication.id });
  }

  private addUser(email: string, displayName: string, password: string, roles: Array<'LEARNER' | 'ADMIN'>) {
    const user: UserRecord = { id: randomUUID(), email: email.toLowerCase(), displayName, passwordHash: hashPasswordSync(password), roles, avatarUrl: null, createdAt: nowIso() };
    this.users.set(user.id, user); return user;
  }

  userResponse(user: UserRecord) { return { id: user.id, email: user.email, display_name: user.displayName, roles: user.roles, avatar_url: user.avatarUrl, email_verified: true, created_at: user.createdAt }; }
  getUser(id: string) { const value = this.users.get(id); if (!value) throw new NotFoundError('User not found'); return value; }
  async authenticate(email: string, password: string) { const user = [...this.users.values()].find((item) => item.email === email.toLowerCase()); if (!user || !(await verifyPassword(password, user.passwordHash))) return null; return user; }
  register(input: { email: string; password: string; display_name: string }) { if ([...this.users.values()].some((user) => user.email === input.email.toLowerCase())) throw new ConflictError('EMAIL_EXISTS', 'Email is already registered'); return this.addUser(input.email, input.display_name, input.password, ['LEARNER']); }
  updateUser(id: string, input: { display_name?: string; avatar_url?: string | null }) { const user = this.getUser(id); if (input.display_name !== undefined) user.displayName = input.display_name; if (input.avatar_url !== undefined) user.avatarUrl = input.avatar_url; return this.userResponse(user); }
  createRefresh(userId: string, familyId: string = randomUUID()) { const token = randomUUID() + randomUUID(); this.refreshTokens.set(token, { userId, familyId, expiresAt: addDays(new Date(), 30).getTime() }); return token; }
  rotateRefresh(token: string) { const session = this.refreshTokens.get(token); if (!session || session.expiresAt < Date.now()) return null; this.refreshTokens.delete(token); return { user: this.getUser(session.userId), token: this.createRefresh(session.userId, session.familyId) }; }
  revokeRefresh(token?: string) { if (token) this.refreshTokens.delete(token); }

  private collaboratorFor(userId: string, treeId: string) { return [...this.collaborators.values()].find((item) => item.treeId === treeId && item.userId === userId && item.status === 'ACCEPTED'); }
  accessRole(userId: string, tree: TreeRecord): AccessRole | null { const user = this.getUser(userId); if (user.roles.includes('ADMIN')) return 'ADMIN'; if (tree.ownerId === userId) return 'OWNER'; return this.collaboratorFor(userId, tree.id)?.role ?? null; }
  assertView(userId: string, tree: TreeRecord) { const role = this.accessRole(userId, tree); if (!role) throw new ForbiddenError(); return role; }
  assertEdit(userId: string, tree: TreeRecord) { const role = this.assertView(userId, tree); if (!['ADMIN', 'OWNER', 'EDITOR'].includes(role)) throw new ForbiddenError('Edit permission is required'); return role; }
  assertOwner(userId: string, tree: TreeRecord) { const role = this.assertView(userId, tree); if (!['ADMIN', 'OWNER'].includes(role)) throw new ForbiddenError('Owner permission is required'); return role; }

  private revision(tree: TreeRecord) { const has = tree.publishedRevision !== null && tree.draftRevision > tree.publishedRevision; return { draft_revision: tree.draftRevision, published_revision: tree.publishedRevision, has_unpublished_changes: has, state: tree.publishedRevision === null ? 'PRIVATE' : has ? 'DRAFT' : 'PUBLISHED', published_at: tree.publishedAt }; }
  private capabilities(role: AccessRole, target?: NodeRecord) {
    const edit = ['ADMIN', 'OWNER', 'EDITOR'].includes(role); const owner = ['ADMIN', 'OWNER'].includes(role);
    const disabled: Record<string, string> = {};
    if (target?.nodeType === 'VOCABULARY') disabled.add_child = 'VOCABULARY nodes cannot contain child Topics.';
    if (!edit) { disabled.edit = 'Viewer access is read-only.'; disabled.move = 'Viewer access is read-only.'; }
    if (!owner) { disabled.publish = 'Only the owner or admin may publish.'; disabled.delete = 'Only the owner or admin may delete the tree.'; disabled.manage_collaborators = 'Only the owner or admin may manage collaborators.'; }
    return { can_view: true, can_edit: edit, can_add_child: edit && target?.nodeType !== 'VOCABULARY', can_manage_vocabulary: edit && (!target || target.nodeType === 'VOCABULARY'), can_move: edit, can_delete: owner || (!!target && edit), can_publish: owner, can_unpublish: owner, can_clone: true, can_manage_collaborators: owner, disabled_reasons: disabled };
  }
  private activeTree(id: string) { const tree = this.trees.get(id); if (!tree || tree.deletedAt) throw new NotFoundError('Topic tree not found'); return tree; }
  private activeNode(id: string) { const node = this.nodes.get(id); if (!node || node.deletedAt) throw new NotFoundError('Topic node not found'); return node; }
  private activeVocabulary(id: string) { const item = this.vocabularies.get(id); if (!item || item.deletedAt) throw new NotFoundError('Vocabulary not found'); return item; }
  private touchTree(tree: TreeRecord) { tree.draftRevision += 1; tree.version += 1; tree.updatedAt = nowIso(); }
  private children(parentId: string | null, treeId: string) { return [...this.nodes.values()].filter((node) => !node.deletedAt && node.treeId === treeId && node.parentId === parentId).sort((a, b) => a.position - b.position); }
  private descendants(nodeId: string): NodeRecord[] { const result: NodeRecord[] = []; const walk = (id: string) => { for (const child of [...this.nodes.values()].filter((n) => !n.deletedAt && n.parentId === id)) { result.push(child); walk(child.id); } }; walk(nodeId); return result; }
  private ancestors(node: NodeRecord) { const result: NodeRecord[] = []; let current = node.parentId ? this.nodes.get(node.parentId) : undefined; while (current && !current.deletedAt) { result.unshift(current); current = current.parentId ? this.nodes.get(current.parentId) : undefined; } return result; }
  private depth(node: NodeRecord) { return this.ancestors(node).length + 1; }
  private nodeVocabulary(nodeId: string) { return [...this.vocabularies.values()].filter((item) => !item.deletedAt && item.topicNodeId === nodeId); }
  private treeVocabulary(treeId: string) { const nodeIds = new Set([...this.nodes.values()].filter((n) => !n.deletedAt && n.treeId === treeId).map((n) => n.id)); return [...this.vocabularies.values()].filter((item) => !item.deletedAt && nodeIds.has(item.topicNodeId)); }
  private treeResponseFor(userId: string, tree: TreeRecord) { const role = this.assertView(userId, tree); const nodes = [...this.nodes.values()].filter((n) => !n.deletedAt && n.treeId === tree.id); return { id: tree.id, display_name: tree.displayName, description: tree.description, kind: tree.kind, owner: PUBLIC_USER_FIELDS(this.getUser(tree.ownerId)), root_node_count: nodes.filter((n) => n.parentId === null).length, node_count: nodes.length, vocabulary_count: this.treeVocabulary(tree.id).length, max_depth: nodes.reduce((max, n) => Math.max(max, this.depth(n)), 0), revision: this.revision(tree), access_role: role, version: tree.version, capabilities: this.capabilities(role), created_at: tree.createdAt, updated_at: tree.updatedAt }; }
  private nodeResponseFor(userId: string, node: NodeRecord) { const tree = this.activeTree(node.treeId); const role = this.assertView(userId, tree); const ancestors = this.ancestors(node); return { id: node.id, tree_id: node.treeId, parent_id: node.parentId, display_name: node.displayName, description: node.description, node_type: node.nodeType, position: node.position, depth: ancestors.length + 1, has_children: this.children(node.id, node.treeId).length > 0, child_count: this.children(node.id, node.treeId).length, vocabulary_count: this.nodeVocabulary(node.id).length, ancestor_path: ancestors.map((a) => ({ id: a.id, display_name: a.displayName })), path_text: [...ancestors.map((a) => a.displayName), node.displayName].join(' / '), revision: this.revision(tree), is_system: tree.kind === 'DEFAULT', version: node.version, capabilities: this.capabilities(role, node), updated_at: node.updatedAt }; }
  private vocabularyResponse(item: VocabularyRecord) { return { id: item.id, topic_node_id: item.topicNodeId, concept_id: item.conceptId, concept_key: item.conceptKey, english: item.english, vietnamese: item.vietnamese, pronunciation: item.pronunciation, part_of_speech: item.partOfSpeech, example: item.example, image_url: item.imageUrl, audio_url: item.audioUrl, learning_status: 'NEW', version: item.version, created_at: item.createdAt, updated_at: item.updatedAt }; }

  listTrees(userId: string, query: Record<string, unknown> = {}) { let items = [...this.trees.values()].filter((tree) => !tree.deletedAt && this.accessRole(userId, tree)); const q = String(query.q ?? '').trim().toLowerCase(); if (q) items = items.filter((tree) => `${tree.displayName} ${tree.description ?? ''}`.toLowerCase().includes(q)); const page = Number(query.page ?? 1), pageSize = Number(query.page_size ?? 20); const mapped = items.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map((tree) => this.treeResponseFor(userId, tree)); return paginate(mapped, page, pageSize); }
  createTree(userId: string, input: { display_name: string; description?: string | null }, kind: 'DEFAULT' | 'USER' = 'USER') { const now = nowIso(); const tree: TreeRecord = { id: randomUUID(), displayName: input.display_name, description: input.description ?? null, kind, ownerId: userId, draftRevision: 1, publishedRevision: null, publishedAt: null, version: 1, createdAt: now, updatedAt: now, deletedAt: null }; this.trees.set(tree.id, tree); this.audit(userId, 'TREE_CREATED', 'TOPIC_TREE', tree.id, null, { display_name: tree.displayName }); return this.treeResponseFor(userId, tree); }
  getTree(userId: string, treeId: string) { return this.treeResponseFor(userId, this.activeTree(treeId)); }
  getTreeVersion(treeId: string) { return this.activeTree(treeId).version; }
  updateTree(userId: string, treeId: string, input: { display_name?: string; description?: string | null }) { const tree = this.activeTree(treeId); this.assertEdit(userId, tree); const before = { display_name: tree.displayName, description: tree.description }; if (input.display_name !== undefined) tree.displayName = input.display_name; if (input.description !== undefined) tree.description = input.description; this.touchTree(tree); this.audit(userId, 'TREE_UPDATED', 'TOPIC_TREE', tree.id, before, input); return this.treeResponseFor(userId, tree); }
  deleteTree(userId: string, treeId: string) { const tree = this.activeTree(treeId); this.assertOwner(userId, tree); tree.deletedAt = nowIso(); tree.version += 1; this.audit(userId, 'TREE_DELETED', 'TOPIC_TREE', tree.id, null, null); }
  workspace(userId: string, treeId: string) { const tree = this.activeTree(treeId); const roots = this.children(null, tree.id).map((node) => this.nodeResponseFor(userId, node)); const all = [...this.nodes.values()].filter((node) => !node.deletedAt && node.treeId === tree.id); const revision = this.revision(tree); return { tree: this.treeResponseFor(userId, tree), root_nodes: roots, facets: { scope: { all: all.length, roots: roots.length }, status: { [revision.state]: all.length }, node_type: { GROUP: all.filter((n) => n.nodeType === 'GROUP').length, VOCABULARY: all.filter((n) => n.nodeType === 'VOCABULARY').length } }, server_time: nowIso() }; }
  listNodes(userId: string, treeId: string, parentId: string | null, limit = 50, cursor?: string) { const tree = this.activeTree(treeId); this.assertView(userId, tree); const all = this.children(parentId, treeId); const offset = cursor ? Number(Buffer.from(cursor, 'base64url').toString('utf8')) || 0 : 0; const items = all.slice(offset, offset + limit).map((node) => this.nodeResponseFor(userId, node)); const next = offset + items.length; return { items, meta: { limit, next_cursor: next < all.length ? Buffer.from(String(next)).toString('base64url') : null, has_more: next < all.length } }; }
  createNode(userId: string, treeId: string, input: { parent_id?: string | null; display_name: string; description?: string | null; node_type: 'GROUP' | 'VOCABULARY'; position?: number | null }) { const tree = this.activeTree(treeId); this.assertEdit(userId, tree); if (input.parent_id) { const parent = this.activeNode(input.parent_id); if (parent.treeId !== treeId) throw new ValidationError('Parent must belong to the same tree'); if (parent.nodeType !== 'GROUP') throw new ConflictError('INVALID_PARENT_TYPE', 'VOCABULARY nodes cannot contain child Topics'); if (this.depth(parent) + 1 > MAX_DEPTH) throw new ConflictError('MAX_DEPTH_EXCEEDED', `Maximum depth is ${MAX_DEPTH}`); }
    const siblings = this.children(input.parent_id ?? null, treeId); const now = nowIso(); const node: NodeRecord = { id: randomUUID(), treeId, parentId: input.parent_id ?? null, displayName: input.display_name, description: input.description ?? null, nodeType: input.node_type, position: input.position ?? siblings.length, version: 1, updatedAt: now, deletedAt: null }; this.nodes.set(node.id, node); this.touchTree(tree); this.audit(userId, 'NODE_CREATED', 'TOPIC_NODE', node.id, null, { display_name: node.displayName }); return this.nodeResponseFor(userId, node); }
  getNode(userId: string, nodeId: string) { return this.nodeResponseFor(userId, this.activeNode(nodeId)); }
  getNodeVersion(nodeId: string) { return this.activeNode(nodeId).version; }
  updateNode(userId: string, nodeId: string, input: { display_name?: string; description?: string | null; node_type?: 'GROUP' | 'VOCABULARY' }) { const node = this.activeNode(nodeId); const tree = this.activeTree(node.treeId); this.assertEdit(userId, tree); if (input.node_type === 'VOCABULARY' && this.children(node.id, node.treeId).length) throw new ConflictError('NODE_HAS_CHILDREN', 'A GROUP with children cannot be converted to VOCABULARY'); if (input.node_type === 'GROUP' && this.nodeVocabulary(node.id).length) throw new ConflictError('NODE_HAS_VOCABULARY', 'A VOCABULARY node containing words cannot be converted to GROUP'); const before = { display_name: node.displayName, description: node.description, node_type: node.nodeType }; if (input.display_name !== undefined) node.displayName = input.display_name; if (input.description !== undefined) node.description = input.description; if (input.node_type !== undefined) node.nodeType = input.node_type; node.version += 1; node.updatedAt = nowIso(); this.touchTree(tree); this.audit(userId, 'NODE_UPDATED', 'TOPIC_NODE', node.id, before, input); return this.nodeResponseFor(userId, node); }
  deleteNode(userId: string, nodeId: string) { const node = this.activeNode(nodeId); const tree = this.activeTree(node.treeId); this.assertEdit(userId, tree); const now = nowIso(); node.deletedAt = now; for (const child of this.descendants(nodeId)) child.deletedAt = now; for (const vocab of [node, ...this.descendants(nodeId)].flatMap((n) => this.nodeVocabulary(n.id))) vocab.deletedAt = now; this.touchTree(tree); this.audit(userId, 'NODE_DELETED', 'TOPIC_NODE', node.id, null, null); }
  searchTree(userId: string, treeId: string, query: Record<string, unknown>) { const tree = this.activeTree(treeId); this.assertView(userId, tree); const q = normalizeText(String(query.q ?? '')); let matches = [...this.nodes.values()].filter((node) => !node.deletedAt && node.treeId === treeId); if (q) matches = matches.filter((node) => normalizeText(`${node.displayName} ${node.description ?? ''}`).includes(q)); if (query.node_type) matches = matches.filter((node) => node.nodeType === query.node_type); const ancestors = new Map<string, NodeRecord>(); for (const match of matches) for (const a of this.ancestors(match)) ancestors.set(a.id, a); return { matches: matches.map((n) => this.nodeResponseFor(userId, n)), ancestors: [...ancestors.values()].map((n) => this.nodeResponseFor(userId, n)), suggested_expanded_ids: [...new Set(matches.flatMap((n) => this.ancestors(n).map((a) => a.id)))], total_matches: matches.length }; }
  movePreview(userId: string, nodeId: string, input: { target_parent_id: string | null }) { const node = this.activeNode(nodeId); const tree = this.activeTree(node.treeId); this.assertEdit(userId, tree); const current = this.nodeResponseFor(userId, node); let targetPath: Array<{ id: string; display_name: string }> = []; if (input.target_parent_id) { const parent = this.activeNode(input.target_parent_id); if (parent.treeId !== node.treeId) throw new ValidationError('Target parent must be in the same tree'); if (parent.nodeType !== 'GROUP') throw new ConflictError('INVALID_PARENT_TYPE', 'Target parent must be GROUP'); if (parent.id === node.id || this.descendants(node.id).some((child) => child.id === parent.id)) throw new ConflictError('TREE_CYCLE', 'Move would create a cycle'); targetPath = [...this.ancestors(parent), parent].map((n) => ({ id: n.id, display_name: n.displayName })); const subtreeDepth = Math.max(1, ...[node, ...this.descendants(node.id)].map((n) => this.depth(n) - this.depth(node) + 1)); if (targetPath.length + subtreeDepth > MAX_DEPTH) throw new ConflictError('MAX_DEPTH_EXCEEDED', `Move exceeds maximum depth ${MAX_DEPTH}`); }
    return { valid: true, before_path: current.ancestor_path, after_path: targetPath, affected_node_count: 1 + this.descendants(node.id).length, blocking_issues: [], warnings: [] }; }
  moveNode(userId: string, nodeId: string, input: { target_parent_id: string | null; before_node_id?: string | null; after_node_id?: string | null }) { this.movePreview(userId, nodeId, input); const node = this.activeNode(nodeId); const tree = this.activeTree(node.treeId); node.parentId = input.target_parent_id; const siblings = this.children(node.parentId, node.treeId).filter((n) => n.id !== node.id); let pos = siblings.length; if (input.before_node_id) pos = Math.max(0, siblings.findIndex((n) => n.id === input.before_node_id)); if (input.after_node_id) pos = Math.max(0, siblings.findIndex((n) => n.id === input.after_node_id) + 1); node.position = pos; node.version += 1; node.updatedAt = nowIso(); this.touchTree(tree); this.audit(userId, 'NODE_MOVED', 'TOPIC_NODE', node.id, null, input); return this.nodeResponseFor(userId, node); }

  listVocabularies(userId: string, nodeId: string, query: Record<string, unknown> = {}) { const node = this.activeNode(nodeId); this.assertView(userId, this.activeTree(node.treeId)); if (node.nodeType !== 'VOCABULARY') throw new ConflictError('INVALID_NODE_TYPE', 'Vocabulary can only be listed on VOCABULARY nodes'); let items = this.nodeVocabulary(nodeId); const q = normalizeText(String(query.q ?? '')); if (q) items = items.filter((item) => normalizeText(`${item.english} ${item.vietnamese}`).includes(q)); return paginate(items.map((item) => this.vocabularyResponse(item)), Number(query.page ?? 1), Number(query.page_size ?? 20)); }
  createVocabulary(userId: string, nodeId: string, input: any) { const node = this.activeNode(nodeId); const tree = this.activeTree(node.treeId); this.assertEdit(userId, tree); if (node.nodeType !== 'VOCABULARY') throw new ConflictError('INVALID_NODE_TYPE', 'Vocabulary can only be added to VOCABULARY nodes'); const key = `${normalizeText(input.english)}::${normalizeText(input.sense_key ?? '')}`; if (this.nodeVocabulary(nodeId).some((item) => item.conceptKey === key)) throw new ConflictError('VOCABULARY_DUPLICATE', 'Vocabulary already exists in this Topic'); const now = nowIso(); const item: VocabularyRecord = { id: randomUUID(), topicNodeId: nodeId, conceptId: randomUUID(), conceptKey: key, english: input.english.trim(), vietnamese: input.vietnamese.trim(), pronunciation: input.pronunciation ?? null, partOfSpeech: input.part_of_speech ?? null, example: input.example ?? null, imageUrl: input.image_url ?? null, audioUrl: null, version: 1, createdAt: now, updatedAt: now, deletedAt: null }; this.vocabularies.set(item.id, item); this.touchTree(tree); this.audit(userId, 'VOCABULARY_CREATED', 'VOCABULARY', item.id, null, { english: item.english }); return this.vocabularyResponse(item); }
  getVocabulary(userId: string, id: string) { const item = this.activeVocabulary(id); const node = this.activeNode(item.topicNodeId); this.assertView(userId, this.activeTree(node.treeId)); return this.vocabularyResponse(item); }
  getVocabularyVersion(id: string) { return this.activeVocabulary(id).version; }
  updateVocabulary(userId: string, id: string, input: any) { const item = this.activeVocabulary(id); const node = this.activeNode(item.topicNodeId); const tree = this.activeTree(node.treeId); this.assertEdit(userId, tree); for (const [key, prop] of [['english','english'],['vietnamese','vietnamese'],['pronunciation','pronunciation'],['part_of_speech','partOfSpeech'],['example','example'],['image_url','imageUrl']] as const) if (input[key] !== undefined) (item as any)[prop] = input[key]; item.conceptKey = `${normalizeText(item.english)}::${normalizeText(input.sense_key ?? '')}`; item.version += 1; item.updatedAt = nowIso(); this.touchTree(tree); this.audit(userId, 'VOCABULARY_UPDATED', 'VOCABULARY', item.id, null, input); return this.vocabularyResponse(item); }
  deleteVocabulary(userId: string, id: string) { const item = this.activeVocabulary(id); const node = this.activeNode(item.topicNodeId); const tree = this.activeTree(node.treeId); this.assertEdit(userId, tree); item.deletedAt = nowIso(); item.version += 1; this.touchTree(tree); this.audit(userId, 'VOCABULARY_DELETED', 'VOCABULARY', item.id, null, null); }
  searchVocabulary(userId: string, query: Record<string, unknown>) { const accessible = new Set([...this.trees.values()].filter((tree) => !tree.deletedAt && this.accessRole(userId, tree)).map((tree) => tree.id)); const nodeIds = new Set([...this.nodes.values()].filter((n) => !n.deletedAt && accessible.has(n.treeId)).map((n) => n.id)); let items = [...this.vocabularies.values()].filter((v) => !v.deletedAt && nodeIds.has(v.topicNodeId)); const q = normalizeText(String(query.q ?? '')); if (q) items = items.filter((v) => normalizeText(`${v.english} ${v.vietnamese}`).includes(q)); return paginate(items.map((item) => this.vocabularyResponse(item)), Number(query.page ?? 1), Number(query.page_size ?? 20)); }

  publicationPreview(userId: string, treeId: string, input: { scope: 'TREE' | 'BRANCH'; root_node_id?: string | null }) { const tree = this.activeTree(treeId); this.assertOwner(userId, tree); const root = input.scope === 'BRANCH' ? this.activeNode(String(input.root_node_id)) : this.children(null, treeId)[0]; if (!root) throw new ValidationError('Tree has no publishable nodes'); if (root.treeId !== treeId) throw new ValidationError('Root node must belong to the tree'); const scopeNodes = input.scope === 'TREE' ? [...this.nodes.values()].filter((n) => !n.deletedAt && n.treeId === treeId) : [root, ...this.descendants(root.id)]; const nodeIds = new Set(scopeNodes.map((n) => n.id)); return { scope: input.scope, root_node: this.nodeResponseFor(userId, root), node_count: scopeNodes.length, vocabulary_count: [...this.vocabularies.values()].filter((v) => !v.deletedAt && nodeIds.has(v.topicNodeId)).length, blocking_issues: [], warnings: scopeNodes.some((n) => n.nodeType === 'VOCABULARY' && this.nodeVocabulary(n.id).length === 0) ? ['Some vocabulary Topics are empty.'] : [], estimated_index_seconds: Math.max(1, Math.ceil(scopeNodes.length / 100)) }; }
  private publicationResponse(publication: PublicationRecord) { const scopeNodes = publication.scope === 'TREE' ? [...this.nodes.values()].filter((n) => !n.deletedAt && n.treeId === publication.sourceTreeId) : [this.activeNode(publication.sourceRootNodeId!), ...this.descendants(publication.sourceRootNodeId!)]; const ids = new Set(scopeNodes.map((n) => n.id)); const tree = this.activeTree(publication.sourceTreeId); return { id: publication.id, source_tree_id: publication.sourceTreeId, source_root_node_id: publication.sourceRootNodeId, scope: publication.scope, display_name: publication.displayName, description: publication.description, slug: publication.slug, status: publication.status, published_revision: publication.publishedRevision, node_count: scopeNodes.length, vocabulary_count: [...this.vocabularies.values()].filter((v) => !v.deletedAt && ids.has(v.topicNodeId)).length, clone_count: publication.cloneCount, author: PUBLIC_USER_FIELDS(this.getUser(tree.ownerId)), published_at: publication.publishedAt, unpublished_at: publication.unpublishedAt }; }
  publish(userId: string, treeId: string, input: any) { const tree = this.activeTree(treeId); this.assertOwner(userId, tree); if (input.draft_revision !== tree.draftRevision) throw new ConflictError('REVISION_MISMATCH', 'draft_revision does not match current tree revision', { current_revision: tree.draftRevision }); this.publicationPreview(userId, treeId, input); const existing = [...this.publications.values()].find((p) => p.sourceTreeId === treeId && p.sourceRootNodeId === (input.root_node_id ?? null) && p.scope === input.scope && p.status === 'PUBLISHED'); if (existing) { existing.publishedRevision = tree.draftRevision; existing.displayName = input.display_name ?? existing.displayName; existing.description = input.description ?? existing.description; existing.publishedAt = nowIso(); tree.publishedRevision = tree.draftRevision; tree.publishedAt = existing.publishedAt; return this.publicationResponse(existing); }
    const publication: PublicationRecord = { id: randomUUID(), sourceTreeId: treeId, sourceRootNodeId: input.scope === 'BRANCH' ? input.root_node_id : null, scope: input.scope, displayName: input.display_name ?? (input.scope === 'BRANCH' ? this.activeNode(input.root_node_id).displayName : tree.displayName), description: input.description ?? tree.description, slug: `${slugify(input.display_name ?? tree.displayName)}-${randomUUID().slice(0,8)}`, status: 'PUBLISHED', publishedRevision: tree.draftRevision, cloneCount: 0, publishedAt: nowIso(), unpublishedAt: null }; this.publications.set(publication.id, publication); tree.publishedRevision = tree.draftRevision; tree.publishedAt = publication.publishedAt; this.audit(userId, 'PUBLICATION_CREATED', 'PUBLICATION', publication.id, null, { scope: publication.scope }); return this.publicationResponse(publication); }
  listPublications(userId: string, treeId: string, query: Record<string, unknown> = {}) { const tree = this.activeTree(treeId); this.assertView(userId, tree); const items = [...this.publications.values()].filter((p) => p.sourceTreeId === treeId).map((p) => this.publicationResponse(p)); return paginate(items, Number(query.page ?? 1), Number(query.page_size ?? 20)); }
  unpublish(userId: string, publicationId: string) { const publication = this.publications.get(publicationId); if (!publication) throw new NotFoundError('Publication not found'); this.assertOwner(userId, this.activeTree(publication.sourceTreeId)); publication.status = 'UNPUBLISHED'; publication.unpublishedAt = nowIso(); this.audit(userId, 'PUBLICATION_UNPUBLISHED', 'PUBLICATION', publication.id, null, null); return this.publicationResponse(publication); }
  listPublicLibrary(query: Record<string, unknown> = {}) { let items = [...this.publications.values()].filter((p) => p.status === 'PUBLISHED'); const q = normalizeText(String(query.q ?? '')); if (q) items = items.filter((p) => normalizeText(`${p.displayName} ${p.description ?? ''}`).includes(q)); const mapped = items.map((p) => ({ ...this.publicationResponse(p), level: p.displayName.includes('A1') ? 'A1' : null, tags: ['vocabulary', p.scope.toLowerCase()], can_clone: true, updated_at: p.publishedAt })); return paginate(mapped, Number(query.page ?? 1), Number(query.page_size ?? 20)); }
  getPublicItem(publicationId: string) { const p = this.publications.get(publicationId); if (!p || p.status !== 'PUBLISHED') throw new NotFoundError('Public item not found'); return { ...this.publicationResponse(p), level: p.displayName.includes('A1') ? 'A1' : null, tags: ['vocabulary', p.scope.toLowerCase()], can_clone: true, updated_at: p.publishedAt }; }
  listPublicNodes(publicationId: string, parentId: string | null, limit = 50, cursor?: string) { const p = this.publications.get(publicationId); if (!p || p.status !== 'PUBLISHED') throw new NotFoundError('Public item not found'); const tree = this.activeTree(p.sourceTreeId); const ownerId = tree.ownerId; const allowed = p.scope === 'TREE' ? new Set([...this.nodes.values()].filter((n) => !n.deletedAt && n.treeId === tree.id).map((n) => n.id)) : new Set([p.sourceRootNodeId!, ...this.descendants(p.sourceRootNodeId!).map((n) => n.id)]); const effectiveParent = parentId; if (!effectiveParent && p.scope === 'BRANCH') { const root = this.activeNode(p.sourceRootNodeId!); return { items: [this.nodeResponseFor(ownerId, root)], meta: { limit, next_cursor: null, has_more: false } }; }
    const all = this.children(effectiveParent, tree.id).filter((n) => allowed.has(n.id)); const offset = cursor ? Number(Buffer.from(cursor, 'base64url').toString()) || 0 : 0; const items = all.slice(offset, offset + limit).map((n) => this.nodeResponseFor(ownerId, n)); return { items, meta: { limit, next_cursor: offset + items.length < all.length ? Buffer.from(String(offset + items.length)).toString('base64url') : null, has_more: offset + items.length < all.length } }; }
  clonePublic(userId: string, publicationId: string, input: { display_name?: string | null }) { const p = this.publications.get(publicationId); if (!p || p.status !== 'PUBLISHED') throw new NotFoundError('Public item not found'); const sourceTree = this.activeTree(p.sourceTreeId); const target = this.createTree(userId, { display_name: input.display_name ?? `${p.displayName} (Copy)`, description: p.description }); const targetTree = this.activeTree(target.id); const sourceNodes = p.scope === 'TREE' ? [...this.nodes.values()].filter((n) => !n.deletedAt && n.treeId === sourceTree.id) : [this.activeNode(p.sourceRootNodeId!), ...this.descendants(p.sourceRootNodeId!)]; const sourceIds = new Set(sourceNodes.map((n) => n.id)); const mapping = new Map<string, string>(); for (const source of sourceNodes.sort((a,b)=>this.depth(a)-this.depth(b) || a.position-b.position)) { const copy: NodeRecord = { ...source, id: randomUUID(), treeId: targetTree.id, parentId: source.parentId && sourceIds.has(source.parentId) ? mapping.get(source.parentId)! : null, version: 1, updatedAt: nowIso(), deletedAt: null }; mapping.set(source.id, copy.id); this.nodes.set(copy.id, copy); }
    for (const vocab of [...this.vocabularies.values()].filter((v) => !v.deletedAt && sourceIds.has(v.topicNodeId))) { const copy: VocabularyRecord = { ...vocab, id: randomUUID(), conceptId: randomUUID(), topicNodeId: mapping.get(vocab.topicNodeId)!, version: 1, createdAt: nowIso(), updatedAt: nowIso(), deletedAt: null }; this.vocabularies.set(copy.id, copy); }
    targetTree.draftRevision = 1; targetTree.version = 1; p.cloneCount += 1; return this.createOperation(userId, 'TREE_CLONE', { tree_id: targetTree.id, source_publication_id: publicationId }); }

  listCollaborators(userId: string, treeId: string, query: Record<string, unknown> = {}) { const tree = this.activeTree(treeId); this.assertView(userId, tree); const items = [...this.collaborators.values()].filter((c) => c.treeId === treeId && c.status !== 'REVOKED').map((c) => this.collaboratorResponse(c)); return paginate(items, Number(query.page ?? 1), Number(query.page_size ?? 20)); }
  private collaboratorResponse(c: CollaboratorRecord) { return { id: c.id, tree_id: c.treeId, user: c.userId ? PUBLIC_USER_FIELDS(this.getUser(c.userId)) : null, email: c.email, role: c.role, status: c.status, created_at: c.createdAt, accepted_at: c.acceptedAt }; }
  inviteCollaborator(userId: string, treeId: string, input: { email: string; role: 'EDITOR' | 'VIEWER' }) { const tree = this.activeTree(treeId); this.assertOwner(userId, tree); if ([...this.collaborators.values()].some((c) => c.treeId === treeId && c.email === input.email.toLowerCase() && !['REVOKED','EXPIRED'].includes(c.status))) throw new ConflictError('COLLABORATOR_EXISTS', 'Collaborator or invitation already exists'); const invited = [...this.users.values()].find((u) => u.email === input.email.toLowerCase()); const c: CollaboratorRecord = { id: randomUUID(), treeId, userId: invited?.id ?? null, email: input.email.toLowerCase(), role: input.role, status: invited ? 'ACCEPTED' : 'PENDING', token: randomUUID(), createdAt: nowIso(), acceptedAt: invited ? nowIso() : null, version: 1 }; this.collaborators.set(c.id, c); this.audit(userId, 'COLLABORATOR_INVITED', 'COLLABORATOR', c.id, null, { email: c.email, role: c.role }); return this.collaboratorResponse(c); }
  getCollaboratorVersion(id: string) { const c = this.collaborators.get(id); if (!c) throw new NotFoundError('Collaborator not found'); return c.version; }
  updateCollaborator(userId: string, id: string, role: 'EDITOR' | 'VIEWER') { const c = this.collaborators.get(id); if (!c) throw new NotFoundError('Collaborator not found'); this.assertOwner(userId, this.activeTree(c.treeId)); c.role = role; c.version += 1; return this.collaboratorResponse(c); }
  revokeCollaborator(userId: string, id: string) { const c = this.collaborators.get(id); if (!c) throw new NotFoundError('Collaborator not found'); this.assertOwner(userId, this.activeTree(c.treeId)); c.status = 'REVOKED'; c.version += 1; }
  acceptInvitation(userId: string, token: string) { const c = [...this.collaborators.values()].find((item) => item.token === token && item.status === 'PENDING'); if (!c) throw new NotFoundError('Invitation not found or expired'); const user = this.getUser(userId); if (user.email !== c.email) throw new ForbiddenError('Invitation email does not match current account'); c.userId = userId; c.status = 'ACCEPTED'; c.acceptedAt = nowIso(); return this.collaboratorResponse(c); }

  parseBoolean(input: any) { return parseQuery(input.expression, input.aliases, input.universe ?? 'ALIASES_UNION'); }
  previewBoolean(userId: string, input: any) { const parse = this.parseBoolean(input); if (!parse.valid) return { parse, result_count: 0, items: [], meta: { page: 1, page_size: input.page_size ?? 20, total_items: 0, total_pages: 0 }, source_versions: {}, truncated: false }; const aliasSets: Record<string, Set<string>> = {}; const sourceVersions: Record<string, number> = {}; for (const alias of input.aliases) { const node = this.activeNode(alias.topic_node_id); this.assertView(userId, this.activeTree(node.treeId)); const nodeIds = new Set([node.id, ...this.descendants(node.id).map((n) => n.id)]); aliasSets[alias.alias.toUpperCase()] = new Set([...this.vocabularies.values()].filter((v) => !v.deletedAt && nodeIds.has(v.topicNodeId)).map((v) => v.id)); sourceVersions[alias.topic_node_id] = node.version; }
    const allAccessible = new Set(this.searchVocabulary(userId, { page: 1, page_size: 100 }).items.map((v: any) => v.id)); const ids = evaluateQuery(parse.ast as any, aliasSets, input.universe === 'ALL_ACCESSIBLE' ? allAccessible : new Set(Object.values(aliasSets).flatMap((s) => [...s]))); const values = [...ids].map((id) => this.vocabularyResponse(this.activeVocabulary(id))); const page = Number(input.page ?? 1), pageSize = Number(input.page_size ?? 20); const result = paginate(values, page, pageSize); return { parse, result_count: values.length, items: result.items, meta: result.meta, source_versions: sourceVersions, truncated: false }; }
  listSavedQueries(userId: string, query: Record<string, unknown> = {}) { const values = [...this.savedQueries.values()].filter((q) => q.userId === userId).map((q) => this.savedQueryResponse(q)); return paginate(values, Number(query.page ?? 1), Number(query.page_size ?? 20)); }
  private savedQueryResponse(q: SavedQueryRecord) { return { id: q.id, display_name: q.displayName, mode: q.mode, visibility: q.visibility, expression: q.expression, normalized_expression: q.normalizedExpression, ast: q.ast, universe: q.universe, aliases: q.aliases, result_count: q.resultCount, version: q.version, created_at: q.createdAt, updated_at: q.updatedAt }; }
  createSavedQuery(userId: string, input: any) { const parse = this.parseBoolean(input); if (!parse.valid) throw new ValidationError('Boolean expression is invalid', { errors: parse.errors }); const preview = this.previewBoolean(userId, { ...input, page: 1, page_size: 1 }); const now = nowIso(); const q: SavedQueryRecord = { id: randomUUID(), userId, displayName: input.display_name, mode: input.mode, visibility: input.visibility ?? 'PRIVATE', expression: input.expression, normalizedExpression: parse.normalized_expression!, ast: parse.ast, universe: input.universe, aliases: input.aliases, resultCount: preview.result_count, version: 1, createdAt: now, updatedAt: now }; this.savedQueries.set(q.id, q); return this.savedQueryResponse(q); }
  getSavedQuery(userId: string, id: string) { const q = this.savedQueries.get(id); if (!q || q.userId !== userId) throw new NotFoundError('Saved query not found'); return this.savedQueryResponse(q); }
  getSavedQueryVersion(id: string) { const q = this.savedQueries.get(id); if (!q) throw new NotFoundError('Saved query not found'); return q.version; }
  updateSavedQuery(userId: string, id: string, input: any) { const q = this.savedQueries.get(id); if (!q || q.userId !== userId) throw new NotFoundError('Saved query not found'); const parse = this.parseBoolean(input); if (!parse.valid) throw new ValidationError('Boolean expression is invalid'); Object.assign(q, { displayName: input.display_name, mode: input.mode, visibility: input.visibility ?? 'PRIVATE', expression: input.expression, normalizedExpression: parse.normalized_expression!, ast: parse.ast, universe: input.universe, aliases: input.aliases, version: q.version + 1, updatedAt: nowIso() }); return this.savedQueryResponse(q); }
  deleteSavedQuery(userId: string, id: string) { const q = this.savedQueries.get(id); if (!q || q.userId !== userId) throw new NotFoundError('Saved query not found'); this.savedQueries.delete(id); }

  createImport(userId: string, nodeId: string, rows: ImportRowRecord[]) { const node = this.activeNode(nodeId); this.assertEdit(userId, this.activeTree(node.treeId)); if (node.nodeType !== 'VOCABULARY') throw new ConflictError('INVALID_IMPORT_TARGET', 'Import target must be a VOCABULARY node'); const op = this.createOperation(userId, 'IMPORT_VALIDATE', { rows: rows.length }); const job: ImportJobRecord = { id: randomUUID(), userId, topicNodeId: nodeId, operationId: op.id, status: 'READY', rows, createdAt: nowIso(), updatedAt: nowIso(), expiresAt: addDays(new Date(), 2).toISOString(), createdCount: 0, skippedCount: 0 }; this.imports.set(job.id, job); return this.importResponse(job); }
  private importResponse(job: ImportJobRecord) { const counts = { total_rows: job.rows.length, valid_rows: job.rows.filter((r) => r.status === 'VALID').length, warning_rows: job.rows.filter((r) => r.status === 'WARNING').length, error_rows: job.rows.filter((r) => r.status === 'ERROR').length, created_count: job.createdCount, skipped_count: job.skippedCount }; return { id: job.id, topic_node_id: job.topicNodeId, operation_id: job.operationId, status: job.status, summary: counts, expires_at: job.expiresAt, created_at: job.createdAt, updated_at: job.updatedAt }; }
  getImport(userId: string, id: string) { const job = this.imports.get(id); if (!job || job.userId !== userId) throw new NotFoundError('Import job not found'); return this.importResponse(job); }
  importPreview(userId: string, id: string, query: Record<string, unknown> = {}) { const job = this.imports.get(id); if (!job || job.userId !== userId) throw new NotFoundError('Import job not found'); return paginate(job.rows, Number(query.page ?? 1), Number(query.page_size ?? 50)); }
  commitImport(userId: string, id: string, input: any) { const job = this.imports.get(id); if (!job || job.userId !== userId) throw new NotFoundError('Import job not found'); if (job.status === 'COMPLETED') return this.createOperation(userId, 'IMPORT_COMMIT', { import_id: id, created_count: job.createdCount }); const errors = job.rows.filter((r) => r.status === 'ERROR'); if (input.strategy === 'ALL_OR_NOTHING' && errors.length) throw new ConflictError('IMPORT_HAS_ERRORS', 'ALL_OR_NOTHING cannot commit while errors exist'); job.status = 'COMMITTING'; let created = 0, skipped = 0; for (const row of job.rows.filter((r) => r.status !== 'ERROR')) { try { this.createVocabulary(userId, job.topicNodeId, row.normalized); created += 1; } catch (error) { if (error instanceof ConflictError && input.duplicate_strategy === 'SKIP') skipped += 1; else throw error; } } job.createdCount = created; job.skippedCount = skipped; job.status = 'COMPLETED'; job.updatedAt = nowIso(); return this.createOperation(userId, 'IMPORT_COMMIT', { import_id: id, created_count: created, skipped_count: skipped }); }

  createStudySession(userId: string, input: any) { let vocab: VocabularyRecord[] = []; if (input.source.type === 'TOPIC_NODE') { const node = this.activeNode(input.source.id); this.assertView(userId, this.activeTree(node.treeId)); const ids = new Set([node.id, ...this.descendants(node.id).map((n) => n.id)]); vocab = [...this.vocabularies.values()].filter((v) => !v.deletedAt && ids.has(v.topicNodeId)); } else if (input.source.type === 'SAVED_QUERY') { const q = this.getSavedQuery(userId, input.source.id) as any; vocab = (this.previewBoolean(userId, { ...q, page: 1, page_size: Math.min(input.limit ?? 20, 100) }) as any).items.map((v: any) => this.activeVocabulary(v.id)); } else vocab = [...this.vocabularies.values()].filter((v) => !v.deletedAt).slice(0, input.limit ?? 20);
    const limit = Math.min(Number(input.limit ?? 20), 100); vocab = vocab.slice(0, limit); if (!vocab.length) throw new ConflictError('NO_STUDY_ITEMS', 'No vocabulary is available for this source'); const session: StudySessionRecord = { id: randomUUID(), userId, mode: input.mode, source: input.source, status: 'ACTIVE', itemIds: vocab.map((v) => v.id), currentIndex: 0, correctCount: 0, wrongConceptIds: [], startedAt: nowIso(), completedAt: null }; this.studySessions.set(session.id, session); return this.studyResponse(session); }
  private studyItem(session: StudySessionRecord) { const vocabularyId = session.itemIds[session.currentIndex]; if (!vocabularyId) return null; const v = this.activeVocabulary(vocabularyId); const isViPrompt = session.mode === 'VI_TO_EN' || session.mode === 'LISTEN_EN_WRITE_VI'; const answerType = session.mode === 'FLASHCARD' ? 'SELF_RATE' : session.mode === 'MULTIPLE_CHOICE' ? 'CHOICE' : session.mode === 'PRONUNCIATION' ? 'AUDIO' : 'TEXT'; return { id: v.id, position: session.currentIndex, concept_id: v.conceptId, prompt: { text: isViPrompt ? v.vietnamese : v.english, english: v.english, vietnamese: v.vietnamese, pronunciation: v.pronunciation }, answer_type: answerType, choices: answerType === 'CHOICE' ? [v.vietnamese, ...[...this.vocabularies.values()].filter((x) => x.id !== v.id && !x.deletedAt).slice(0,3).map((x) => x.vietnamese)].sort().map((label) => ({ id: label, label })) : [], audio_url: v.audioUrl, max_replays: session.mode.startsWith('LISTEN') ? 3 : null }; }
  private studyResponse(session: StudySessionRecord) { return { id: session.id, mode: session.mode, source: session.source, status: session.status, total_items: session.itemIds.length, current_index: session.currentIndex, correct_count: session.correctCount, current_item: session.status === 'ACTIVE' ? this.studyItem(session) : null, started_at: session.startedAt, completed_at: session.completedAt }; }
  getStudySession(userId: string, id: string) { const s = this.studySessions.get(id); if (!s || s.userId !== userId) throw new NotFoundError('Study session not found'); return this.studyResponse(s); }
  answerStudy(userId: string, id: string, input: any) { const s = this.studySessions.get(id); if (!s || s.userId !== userId) throw new NotFoundError('Study session not found'); if (s.status !== 'ACTIVE') throw new ConflictError('SESSION_NOT_ACTIVE', 'Study session is not active'); const item = this.studyItem(s)!; if (item.id !== input.item_id) throw new ConflictError('ITEM_MISMATCH', 'Answer item is not the current item'); const v = this.activeVocabulary(item.id); const answerValue = String(input.answer?.value ?? input.answer?.text ?? input.answer?.rating ?? '').trim(); const expected = s.mode === 'VI_TO_EN' || s.mode === 'LISTEN_EN_WRITE_EN' ? v.english : v.vietnamese; const correct = s.mode === 'FLASHCARD' ? ['GOOD','EASY','3','4'].includes(answerValue.toUpperCase()) : normalizeText(answerValue) === normalizeText(expected); if (correct) s.correctCount += 1; else s.wrongConceptIds.push(v.conceptId); s.currentIndex += 1; if (s.currentIndex >= s.itemIds.length) { s.status = 'COMPLETED'; s.completedAt = nowIso(); } return { correct, feedback: { expected, submitted: answerValue }, session: this.studyResponse(s) }; }
  completeStudy(userId: string, id: string) { const s = this.studySessions.get(id); if (!s || s.userId !== userId) throw new NotFoundError('Study session not found'); s.status = 'COMPLETED'; s.completedAt ??= nowIso(); const accuracy = s.itemIds.length ? s.correctCount / s.itemIds.length : 0; return { session_id: s.id, correct_count: s.correctCount, total_items: s.itemIds.length, accuracy, xp_earned: Math.round(s.correctCount * 10 + accuracy * 20), streak_days: 7, wrong_concept_ids: s.wrongConceptIds }; }
  createPronunciation(userId: string, conceptId: string) { const operation = this.createOperation(userId, 'PRONUNCIATION_SCORE', { concept_id: conceptId, score: 86 }); const attempt: PronunciationRecord = { id: randomUUID(), userId, operationId: operation.id, conceptId, status: 'COMPLETED', scores: { overall: 86, pronunciation: 88, fluency: 82 }, feedback: { message: 'Good pronunciation. Focus on the final consonant.' }, createdAt: nowIso(), completedAt: nowIso() }; this.pronunciationAttempts.set(attempt.id, attempt); return this.pronunciationResponse(attempt); }
  private pronunciationResponse(a: PronunciationRecord) { return { id: a.id, operation_id: a.operationId, concept_id: a.conceptId, status: a.status, scores: a.scores, feedback: a.feedback, created_at: a.createdAt, completed_at: a.completedAt }; }
  getPronunciation(userId: string, id: string) { const a = this.pronunciationAttempts.get(id); if (!a || a.userId !== userId) throw new NotFoundError('Pronunciation attempt not found'); return this.pronunciationResponse(a); }

  createOperation(userId: string, type: OperationRecord['type'], result: Record<string, unknown>) { const now = nowIso(); const op: OperationRecord = { id: randomUUID(), userId, type, status: 'SUCCEEDED', progressPercent: 100, result, error: null, createdAt: now, updatedAt: now, completedAt: now }; this.operations.set(op.id, op); return this.operationResponse(op); }
  private operationResponse(op: OperationRecord) { return { id: op.id, type: op.type, status: op.status, progress_percent: op.progressPercent, result: op.result, error: op.error, created_at: op.createdAt, updated_at: op.updatedAt, completed_at: op.completedAt }; }
  getOperation(userId: string, id: string) { const op = this.operations.get(id); if (!op || op.userId !== userId) throw new NotFoundError('Operation not found'); return this.operationResponse(op); }
  getStats(userId: string) { const sessions = [...this.studySessions.values()].filter((s) => s.userId === userId); const total = sessions.reduce((sum,s)=>sum+s.itemIds.length,0); const correct = sessions.reduce((sum,s)=>sum+s.correctCount,0); return { learned: Math.min(this.vocabularies.size, total || 6), mastered: Math.floor(correct / 2), streak_days: 7, xp: correct * 10 + 140, accuracy: total ? correct / total : 0.84, daily_goal: 20, today_completed: Math.min(total,20), continue_session_id: sessions.find((s)=>s.status==='ACTIVE')?.id ?? null }; }
  adminDashboard() { return { draft_trees: [...this.trees.values()].filter((t)=>!t.deletedAt && this.revision(t).state==='DRAFT').length, published_trees: [...this.publications.values()].filter((p)=>p.status==='PUBLISHED').length, content_issues: [...this.nodes.values()].filter((n)=>!n.deletedAt && n.nodeType==='VOCABULARY' && !this.nodeVocabulary(n.id).length).length, pending_imports: [...this.imports.values()].filter((i)=>!['COMPLETED','FAILED','EXPIRED'].includes(i.status)).length, recent_activity: this.auditLogs.slice(-10).reverse() }; }
  contentHealth() { const empty = [...this.nodes.values()].filter((n)=>!n.deletedAt && n.nodeType==='VOCABULARY' && !this.nodeVocabulary(n.id).length); return { empty_vocabulary_nodes: empty.length, duplicate_concepts: 0, missing_pronunciation: [...this.vocabularies.values()].filter((v)=>!v.deletedAt && !v.pronunciation).length, missing_examples: [...this.vocabularies.values()].filter((v)=>!v.deletedAt && !v.example).length, checked_at: nowIso() }; }
  listAudit(query: Record<string, unknown> = {}) { const items = this.auditLogs.slice().reverse().map((a)=>({ id:a.id, actor:a.actorId ? PUBLIC_USER_FIELDS(this.getUser(a.actorId)):null, action:a.action, resource_type:a.resourceType, resource_id:a.resourceId, before:a.before, after:a.after, trace_id:a.traceId, created_at:a.createdAt })); return paginate(items, Number(query.page ?? 1), Number(query.page_size ?? 20)); }
  audit(actorId: string | null, action: string, resourceType: string, resourceId: string | null, before: Record<string, unknown> | null, after: Record<string, unknown> | null, traceId: string | null = null) { this.auditLogs.push({ id: this.auditSequence++, actorId, action, resourceType, resourceId, before, after, traceId, createdAt: nowIso() }); }
}

export const store = new MemoryStore();
